---
# tasks file for capistrano_setup
# Install passlib if required
- name: Install latest passlib with pip
  ansible.builtin.pip: name=passlib

- include_tasks: users.yml
  tags: users

- include_tasks: structure.yml
  tags: structure.yml

- include_tasks: delete.yml
  tags: delete.yml
